import type { Metadata } from "next";
import "./globals.css";

import { Source_Code_Pro } from "next/font/google";
import Header from "@/components/Header";
import Footer from "@/components/Footer";
import RootProviders from "@/provider/RootProvider";
import { ClerkProvider } from "@clerk/nextjs";
import { Toaster } from "sonner";
const roboto = Source_Code_Pro({
  weight: "400",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Typewell",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${roboto.className} bg-background`}>
        <RootProviders>
          <ClerkProvider>
            <Header />
            <main>{children}</main>
            <Footer />
            <Toaster position="bottom-right" />
          </ClerkProvider>
        </RootProviders>
      </body>
    </html>
  );
}
